# Generated by Django 6.0.6 on 2026-06-12 09:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("communications", "0004_conversation_conversationmessage_and_more"),
        ("customers", "0003_customersegment_customersegmentmembership_survey_and_more"),
        ("marketing", "0001_initial"),
        ("organizations", "0003_retentionpolicy"),
    ]

    operations = [
        migrations.CreateModel(
            name="Journey",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("abandoned_booking", "Abandoned Booking"),
                            ("win_back", "Win-Back"),
                            ("birthday", "Birthday"),
                            ("milestone", "Milestone"),
                            ("custom", "Custom"),
                        ],
                        max_length=30,
                    ),
                ),
                ("trigger_config", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=False)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journeys",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ReferralProgram",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "referrer_reward_type",
                    models.CharField(
                        choices=[
                            ("loyalty_points", "Loyalty Points"),
                            ("store_credit", "Store Credit"),
                        ],
                        default="loyalty_points",
                        max_length=20,
                    ),
                ),
                (
                    "referrer_reward_value",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "referee_reward_type",
                    models.CharField(
                        choices=[
                            ("loyalty_points", "Loyalty Points"),
                            ("store_credit", "Store Credit"),
                        ],
                        default="loyalty_points",
                        max_length=20,
                    ),
                ),
                (
                    "referee_reward_value",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "min_referee_spend",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("max_referrals_per_customer", models.PositiveIntegerField(default=20)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referral_programs",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="JourneyStep",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                ("delay_hours", models.PositiveIntegerField(default=0)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("sms", "SMS"),
                            ("email", "Email"),
                            ("whatsapp", "WhatsApp"),
                            ("push", "Push"),
                            ("in_app", "In-App"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "journey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="marketing.journey",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="journey_steps",
                        to="communications.messagetemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["journey", "order"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("journey", "order"), name="uniq_journey_step_order"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Referral",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("qualified", "Qualified"),
                            ("rewarded", "Rewarded"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("qualified_at", models.DateTimeField(blank=True, null=True)),
                ("rewarded_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.CharField(blank=True, max_length=255)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referrals",
                        to="organizations.organization",
                    ),
                ),
                (
                    "referee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referrals_received",
                        to="customers.customer",
                    ),
                ),
                (
                    "referrer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referrals_made",
                        to="customers.customer",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referrals",
                        to="marketing.referralprogram",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "status"],
                        name="marketing_r_organiz_7d0d1c_idx",
                    ),
                    models.Index(
                        fields=["referrer", "status"],
                        name="marketing_r_referre_4293c6_idx",
                    ),
                ],
            },
        ),
    ]
