# Generated by Django 6.0.6 on 2026-06-11 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("communications", "0001_initial"),
        ("customers", "0001_initial"),
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="consentrecord",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consent_records",
                to="customers.customer",
            ),
        ),
        migrations.AddField(
            model_name="consentrecord",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consent_records",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="messagedispatch",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="message_dispatches",
                to="customers.customer",
            ),
        ),
        migrations.AddField(
            model_name="messagedispatch",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="message_dispatches",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="messagetemplate",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="message_templates",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="messagedispatch",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dispatches",
                to="communications.messagetemplate",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="customers.customer",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="notificationtemplate",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification_templates",
                to="organizations.organization",
            ),
        ),
        migrations.AddIndex(
            model_name="messagedispatch",
            index=models.Index(
                fields=["organization", "created_at"],
                name="communicati_organiz_9bedd4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="messagedispatch",
            index=models.Index(
                fields=["organization", "status"], name="communicati_organiz_ee9209_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "read_at"], name="communicati_user_id_4cac3d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["organization", "created_at"],
                name="communicati_organiz_a42481_idx",
            ),
        ),
    ]
