# Generated by Django 6.0.6 on 2026-06-13 23:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("communications", "0004_conversation_conversationmessage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messagedispatch",
            name="external_message_id",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
