# Generated by Django 6.0.6 on 2026-06-12 09:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "organizations",
            "0002_organization_building_number_organization_city_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="RetentionPolicy",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("analytics_events", "Analytics Events"),
                            ("audit_logs", "Audit Logs"),
                            ("access_logs", "Access Logs"),
                            ("message_dispatches", "Message Dispatches"),
                            ("notifications", "Notifications"),
                            ("idempotency_records", "Idempotency Records"),
                            ("slot_holds", "Slot Holds"),
                        ],
                        max_length=50,
                    ),
                ),
                ("retention_days", models.PositiveIntegerField()),
                (
                    "action",
                    models.CharField(
                        choices=[("delete", "Delete"), ("anonymize", "Anonymize")],
                        default="delete",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retention_policies",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "retention policies",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "entity_type"),
                        name="uniq_retention_policy_per_entity",
                    )
                ],
            },
        ),
    ]
