# Generated by Django 6.0.6 on 2026-06-12 09:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commerce", "0004_pricingrule"),
        ("customers", "0003_customersegment_customersegmentmembership_survey_and_more"),
        ("operations", "0001_initial"),
        ("organizations", "0003_retentionpolicy"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="is_saudi",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="employee",
            name="monthly_salary",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name="CommissionRule",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "basis",
                    models.CharField(
                        choices=[
                            ("percent", "Percentage of line total"),
                            ("fixed", "Fixed amount per item"),
                            ("tiered", "Tiered percentage by period revenue"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "rate_percent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "fixed_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("tiers", models.JSONField(blank=True, default=list)),
                (
                    "applies_to",
                    models.CharField(
                        choices=[
                            ("services", "Services"),
                            ("products", "Products"),
                            ("all", "Services & Products"),
                        ],
                        default="all",
                        max_length=10,
                    ),
                ),
                ("priority", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commission_rules",
                        to="organizations.branch",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commission_rules",
                        to="operations.employee",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commission_rules",
                        to="organizations.organization",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commission_rules",
                        to="commerce.product",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commission_rules",
                        to="commerce.service",
                    ),
                ),
            ],
            options={
                "ordering": ["-priority", "name"],
                "indexes": [
                    models.Index(
                        fields=["organization", "is_active"],
                        name="operations__organiz_ae884f_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EmployeeCostComponent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "component_type",
                    models.CharField(
                        choices=[
                            ("base_salary", "Base Salary"),
                            ("gosi_employer", "GOSI (Employer Share)"),
                            ("qiwa_visa", "Qiwa/Visa Amortization"),
                            ("medical_insurance", "Medical Insurance"),
                            ("housing", "Housing Allowance"),
                            ("transport", "Transport Allowance"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "monthly_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cost_components",
                        to="operations.employee",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_cost_components",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-effective_from"],
                "indexes": [
                    models.Index(
                        fields=["employee", "effective_from"],
                        name="operations__employe_40bda2_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WaitlistEntry",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("desired_from", models.DateTimeField()),
                ("desired_until", models.DateTimeField()),
                ("priority", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting"),
                            ("offered", "Offered"),
                            ("booked", "Booked"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="waiting",
                        max_length=20,
                    ),
                ),
                ("offered_at", models.DateTimeField(blank=True, null=True)),
                ("offer_expires_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "booked_appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="waitlist_entries",
                        to="operations.appointment",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waitlist_entries",
                        to="organizations.branch",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waitlist_entries",
                        to="customers.customer",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waitlist_entries",
                        to="organizations.organization",
                    ),
                ),
                (
                    "preferred_employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="waitlist_entries",
                        to="operations.employee",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waitlist_entries",
                        to="commerce.service",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "waitlist entries",
                "ordering": ["-priority", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["branch", "status"],
                        name="operations__branch__b621b7_idx",
                    )
                ],
            },
        ),
    ]
