# Generated by Django 6.0.6 on 2026-06-12 09:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0001_initial"),
        ("organizations", "0003_retentionpolicy"),
    ]

    operations = [
        migrations.AddField(
            model_name="apikey",
            name="key_prefix",
            field=models.CharField(blank=True, db_index=True, max_length=8),
        ),
        migrations.AddField(
            model_name="webhookendpoint",
            name="signing_secret_encrypted",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="OutboundEvent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event_type", models.CharField(max_length=100)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("dispatched_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outbound_events",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="WebhookDelivery",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed (will retry)"),
                            ("dead", "Dead (retries exhausted)"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                (
                    "last_status_code",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("last_error", models.CharField(blank=True, max_length=500)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "endpoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="integrations.webhookendpoint",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="integrations.outboundevent",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "webhook deliveries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IntegrationConnection",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("google_calendar", "Google Calendar"),
                            ("outlook_calendar", "Outlook Calendar"),
                            ("apple_calendar", "Apple Calendar"),
                            ("quickbooks", "QuickBooks"),
                            ("xero", "Xero"),
                            ("mailchimp", "Mailchimp"),
                            ("instagram", "Instagram"),
                            ("facebook", "Facebook"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("connected", "Connected"),
                            ("error", "Error"),
                            ("disconnected", "Disconnected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("external_account_id", models.CharField(blank=True, max_length=255)),
                ("credentials_encrypted", models.TextField(blank=True)),
                ("settings", models.JSONField(blank=True, default=dict)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.CharField(blank=True, max_length=500)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integration_connections",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "provider"),
                        name="uniq_integration_per_provider",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="outboundevent",
            index=models.Index(
                fields=["organization", "event_type"],
                name="integration_organiz_054beb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="outboundevent",
            index=models.Index(
                fields=["dispatched_at"], name="integration_dispatc_ad71ee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="webhookdelivery",
            index=models.Index(
                fields=["status", "created_at"], name="integration_status_f3b913_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="webhookdelivery",
            constraint=models.UniqueConstraint(
                fields=("endpoint", "event"), name="uniq_delivery_per_endpoint_event"
            ),
        ),
    ]
