"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import secrets
from datetime import timedelta
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Populate os.environ from backend/.env before any setting reads it.
# Real environment variables win over .env values (override=False).
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "true").lower() in ("1", "true", "yes")

# SECURITY WARNING: keep the secret key used in production secret!
# Never hardcode a key here — it ends up in version control. Provide
# DJANGO_SECRET_KEY via the environment (see backend/.env.example). In DEBUG
# we mint an ephemeral key per process so local dev needs no setup; this also
# means sessions/JWTs don't survive a restart, which is fine for dev.
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "")
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = "django-insecure-" + secrets.token_urlsafe(50)
    else:
        raise ImproperlyConfigured(
            "DJANGO_SECRET_KEY must be set when DEBUG is off."
        )

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",")
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    # Namaa apps
    "core",
    "accounts",
    "organizations",
    "customers",
    "commerce",
    "inventory",
    "operations",
    "financials",
    "marketing",
    "communications",
    "analytics",
    "ai",
    "integrations",
]

AUTH_USER_MODEL = "accounts.User"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 50,
    "DEFAULT_FILTER_BACKENDS": [
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    # Platform-wide rate limits (per-view overrides tighten these further).
    # Backed by the cache: point CACHES at Redis in production so limits
    # hold across workers.
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        # Dev/test default is effectively unlimited; production deployments
        # set DJANGO_DEBUG=false and get the real limits.
        "anon": os.environ.get("API_THROTTLE_ANON", "60/min"),
        "user": os.environ.get("API_THROTTLE_USER", "600/min"),
        # Dedicated tight limit for login (keyed on IP + email) to blunt
        # brute-force attacks without touching the shared anon bucket.
        "login": os.environ.get("API_THROTTLE_LOGIN", "5/min"),
    },
}

if DEBUG:  # local runs and the test suite share one client IP
    REST_FRAMEWORK["DEFAULT_THROTTLE_RATES"] = {
        "anon": "10000/min",
        "user": "10000/min",
        # Kept tight even in DEBUG so the brute-force guard stays testable.
        "login": os.environ.get("API_THROTTLE_LOGIN", "5/min"),
    }

# JWT auth (djangorestframework-simplejwt). Lifetimes/keys come from env in
# production; the defaults below are development values.
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(
        minutes=int(os.environ.get("JWT_ACCESS_TOKEN_MINUTES", "30"))
    ),
    "REFRESH_TOKEN_LIFETIME": timedelta(
        days=int(os.environ.get("JWT_REFRESH_TOKEN_DAYS", "7"))
    ),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,
    "SIGNING_KEY": os.environ.get("JWT_SIGNING_KEY", SECRET_KEY),
    "AUTH_HEADER_TYPES": ("Bearer",),
}

# Issuer label shown in authenticator apps for TOTP enrollment.
TWO_FACTOR_ISSUER = os.environ.get("TWO_FACTOR_ISSUER", "Namaa")

# Moyasar payment gateway (docs.moyasar.com). Secret values come from env;
# the key is the HTTP Basic username with an empty password, HTTPS only.
MOYASAR_API_BASE_URL = os.environ.get(
    "MOYASAR_API_BASE_URL", "https://api.moyasar.com/v1"
)
MOYASAR_SECRET_KEY = os.environ.get("MOYASAR_SECRET_KEY", "")
MOYASAR_WEBHOOK_SECRET = os.environ.get("MOYASAR_WEBHOOK_SECRET", "")

# Taqnyat SMS gateway (taqnyat.sa, official OpenAPI spec). Bearer token from
# the dashboard; sender must be a pre-approved sender name on the account.
TAQNYAT_API_BASE_URL = os.environ.get("TAQNYAT_API_BASE_URL", "https://api.taqnyat.sa")
TAQNYAT_BEARER_TOKEN = os.environ.get("TAQNYAT_BEARER_TOKEN", "")
TAQNYAT_SMS_SENDER = os.environ.get("TAQNYAT_SMS_SENDER", "")

# WhatsApp via the Meta WhatsApp Cloud API (graph.facebook.com). The Cloud API
# is Meta-hosted (no on-prem servers), the standard direct integration with
# per-message pricing and no BSP markup — the primary channel for the GCC market.
# Values come from Meta App Dashboard > WhatsApp:
# - WHATSAPP_PHONE_NUMBER_ID: the sender number's id (NOT the display number)
# - WHATSAPP_ACCESS_TOKEN: a permanent System User token (not the 24h test token)
# - WHATSAPP_APP_SECRET: signs inbound webhooks (X-Hub-Signature-256)
# - WHATSAPP_WEBHOOK_VERIFY_TOKEN: the string echoed during webhook subscription
# API version is pinned and overridable so upgrades are a config change.
WHATSAPP_API_BASE_URL = os.environ.get(
    "WHATSAPP_API_BASE_URL", "https://graph.facebook.com"
)
WHATSAPP_API_VERSION = os.environ.get("WHATSAPP_API_VERSION", "v21.0")
WHATSAPP_PHONE_NUMBER_ID = os.environ.get("WHATSAPP_PHONE_NUMBER_ID", "")
WHATSAPP_ACCESS_TOKEN = os.environ.get("WHATSAPP_ACCESS_TOKEN", "")
WHATSAPP_APP_SECRET = os.environ.get("WHATSAPP_APP_SECRET", "")
WHATSAPP_WEBHOOK_VERIFY_TOKEN = os.environ.get("WHATSAPP_WEBHOOK_VERIFY_TOKEN", "")

# Email via Amazon SES. Two paths share the same verified identity:
# - Django framework mail (password resets, admin error reports) goes over
#   the SES SMTP interface using the EMAIL_* settings below.
# - Customer-facing dispatches and marketing campaigns go through the SES v2
#   API (communications.gateways.SESEmailClient) so sends are tagged, tracked
#   through a configuration set and reconciled by the SNS event webhook.
# Dev default is the console backend; point DJANGO_EMAIL_BACKEND at the SMTP
# backend in production. SES SMTP credentials are NOT the IAM access keys.
EMAIL_BACKEND = os.environ.get(
    "DJANGO_EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend"
)
EMAIL_HOST = os.environ.get("EMAIL_HOST", "email-smtp.me-south-1.amazonaws.com")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "587"))
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "true").lower() in ("1", "true", "yes")
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
EMAIL_TIMEOUT = int(os.environ.get("EMAIL_TIMEOUT", "10"))
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "Namaa <no-reply@namaa.sa>")
SERVER_EMAIL = os.environ.get("SERVER_EMAIL", DEFAULT_FROM_EMAIL)

# SES v2 API (me-south-1 = Bahrain, the closest region to KSA). Keys may be
# blank on AWS-hosted runtimes where boto3 resolves an instance role instead.
# The configuration set must have an SNS event destination subscribed to
# /api/v1/webhooks/ses/ for delivery tracking; the webhook authenticates
# every envelope against the AWS SNS message signature.
AWS_SES_REGION = os.environ.get("AWS_SES_REGION", "me-south-1")
AWS_ACCESS_KEY_ID = os.environ.get("AWS_ACCESS_KEY_ID", "")
AWS_SECRET_ACCESS_KEY = os.environ.get("AWS_SECRET_ACCESS_KEY", "")
AWS_SES_CONFIGURATION_SET = os.environ.get("AWS_SES_CONFIGURATION_SET", "")
# Exact ARN of the SNS topic carrying SES events. The webhook rejects every
# envelope from any other topic (a valid AWS signature alone is not enough —
# anyone's own topic signs validly too). Blank = webhook fails closed.
AWS_SES_SNS_TOPIC_ARN = os.environ.get("AWS_SES_SNS_TOPIC_ARN", "")
SES_FROM_EMAIL = os.environ.get("SES_FROM_EMAIL", "no-reply@namaa.sa")

# ZATCA Fatoora e-invoicing (Phase 2). ZATCA_ENVIRONMENT picks the API base
# URL and the CSR certificate template: "sandbox" (developer portal, test
# CSIDs), "simulation" (real onboarding flow, no fiscal effect) or
# "production". ZATCA_KEY_ENCRYPTION_KEY is a Fernet key encrypting device
# private keys and CSID secrets at rest — generate one with
# python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
ZATCA_ENVIRONMENT = os.environ.get("ZATCA_ENVIRONMENT", "sandbox")
_ZATCA_BASE_URLS = {
    "sandbox": "https://gw-fatoora.zatca.gov.sa/e-invoicing/developer-portal",
    "simulation": "https://gw-fatoora.zatca.gov.sa/e-invoicing/simulation",
    "production": "https://gw-fatoora.zatca.gov.sa/e-invoicing/core",
}
ZATCA_API_BASE_URL = os.environ.get(
    "ZATCA_API_BASE_URL",
    _ZATCA_BASE_URLS.get(ZATCA_ENVIRONMENT, _ZATCA_BASE_URLS["sandbox"]),
)
ZATCA_KEY_ENCRYPTION_KEY = os.environ.get("ZATCA_KEY_ENCRYPTION_KEY", "")

# Provider-agnostic LLM gateway (ai.gateways.AIClient) over the OpenAI-compatible
# Chat Completions API. Defaults target Groq's free hosted endpoint for testing;
# switch to a local private model by changing ONLY these values — e.g. Ollama:
#   AI_BASE_URL=http://localhost:11434/v1  AI_API_KEY=ollama  AI_MODEL=llama3.1
# Get a free Groq key at https://console.groq.com/keys.
AI_BASE_URL = os.environ.get("AI_BASE_URL", "https://api.groq.com/openai/v1")
AI_API_KEY = os.environ.get("AI_API_KEY", "")
AI_MODEL = os.environ.get("AI_MODEL", "llama-3.3-70b-versatile")
AI_REQUEST_TIMEOUT = float(os.environ.get("AI_REQUEST_TIMEOUT", "60"))

# Celery (settings consumed via config_from_object namespace="CELERY").
# Redis is both broker and result backend; gateway calls and webhook
# processing run on workers so requests never block on third parties.
CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", "redis://localhost:6379/0")
CELERY_RESULT_BACKEND = os.environ.get("CELERY_RESULT_BACKEND", CELERY_BROKER_URL)
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TIMEZONE = "UTC"
CELERY_TASK_ALWAYS_EAGER = os.environ.get(
    "CELERY_TASK_ALWAYS_EAGER", "false"
).lower() in ("1", "true", "yes")
CELERY_TASK_EAGER_PROPAGATES = True

# Periodic recovery sweeps (run a `celery beat` process to activate). These
# re-enqueue webhook events that are still pending or were dead-lettered after
# retries, so a transient outage never permanently strands a paid payment or a
# delivery/bounce receipt. Processing is idempotent, so replay is safe.
CELERY_BEAT_SCHEDULE = {
    "reprocess-stuck-payment-webhooks": {
        "task": "financials.tasks.reprocess_stuck_payment_webhook_events",
        "schedule": 300.0,  # every 5 minutes
    },
    "reprocess-stuck-ses-events": {
        "task": "communications.tasks.reprocess_stuck_ses_events",
        "schedule": 300.0,
    },
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
