from ai import serializers
from ai.models import AIConversation, AIMessage, AIRecommendation
from core.api import TenantScopedViewSet


class AIConversationViewSet(TenantScopedViewSet):
    queryset = AIConversation.objects.select_related("user")
    serializer_class = serializers.AIConversationSerializer
    search_fields = ["title"]


class AIMessageViewSet(TenantScopedViewSet):
    # Append-only chat history.
    http_method_names = ["get", "post", "head", "options"]
    queryset = AIMessage.objects.select_related("conversation")
    serializer_class = serializers.AIMessageSerializer
    org_field = "conversation__organization"
    ordering_fields = ["created_at"]


class AIRecommendationViewSet(TenantScopedViewSet):
    # Recommendations are generated by the AI pipeline; clients update status/dismiss.
    http_method_names = ["get", "patch", "head", "options"]
    queryset = AIRecommendation.objects.all()
    serializer_class = serializers.AIRecommendationSerializer
    ordering_fields = ["created_at"]
