from rest_framework import status
from rest_framework.decorators import action
from rest_framework.exceptions import ValidationError
from rest_framework.response import Response

from ai import serializers
from ai.models import AIConversation, AIMessage, AIRecommendation
from ai.tasks import generate_assistant_reply_task, generate_recommendations_task
from core.api import TenantScopedViewSet, require_org_role


class AIConversationViewSet(TenantScopedViewSet):
    queryset = AIConversation.objects.select_related("user")
    serializer_class = serializers.AIConversationSerializer
    search_fields = ["title"]


class AIMessageViewSet(TenantScopedViewSet):
    # Append-only chat history.
    http_method_names = ["get", "post", "head", "options"]
    queryset = AIMessage.objects.select_related("conversation")
    serializer_class = serializers.AIMessageSerializer
    org_field = "conversation__organization"
    ordering_fields = ["created_at"]

    def perform_create(self, serializer):
        """Persist the message, then answer any user turn on a worker. The
        assistant reply lands as a later message the client polls for, so the
        request never blocks on the LLM."""
        # Enforce tenant ownership of the target conversation before writing:
        # without this a user could append messages to another org's thread
        # (the base ModelViewSet check is bypassed by overriding perform_create).
        self._check_tenant_ownership(serializer)
        message = serializer.save()
        if message.role == AIMessage.Role.USER:
            generate_assistant_reply_task.delay(str(message.conversation_id))


class AIRecommendationViewSet(TenantScopedViewSet):
    # Recommendations are generated by the AI pipeline; clients update status/dismiss.
    http_method_names = ["get", "patch", "head", "options"]
    queryset = AIRecommendation.objects.all()
    serializer_class = serializers.AIRecommendationSerializer
    ordering_fields = ["created_at"]

    @action(detail=False, methods=["post"])
    def generate(self, request):
        """Queue a recommendations refresh for an organization (manager+)."""
        organization_id = request.data.get("organization")
        if not organization_id:
            raise ValidationError({"organization": "This field is required."})
        require_org_role(request.user, organization_id, "manager")
        generate_recommendations_task.delay(str(organization_id))
        return Response(
            {"detail": "Recommendation generation queued."},
            status=status.HTTP_202_ACCEPTED,
        )
