# Generated by Django 6.0.6 on 2026-06-11 18:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyBranchMetric",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("total_bookings", models.PositiveIntegerField(default=0)),
                ("completed_bookings", models.PositiveIntegerField(default=0)),
                ("cancelled_bookings", models.PositiveIntegerField(default=0)),
                ("no_shows", models.PositiveIntegerField(default=0)),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("total_customers", models.PositiveIntegerField(default=0)),
                ("new_customers", models.PositiveIntegerField(default=0)),
                (
                    "avg_wait_time_minutes",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="DailyEmployeeMetric",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("total_appointments", models.PositiveIntegerField(default=0)),
                ("completed_appointments", models.PositiveIntegerField(default=0)),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_commission",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "utilization_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="DailyMetric",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("total_appointments", models.PositiveIntegerField(default=0)),
                ("completed_appointments", models.PositiveIntegerField(default=0)),
                ("cancelled_appointments", models.PositiveIntegerField(default=0)),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("total_customers", models.PositiveIntegerField(default=0)),
                ("new_customers", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=100)),
                ("parameters", models.JSONField(blank=True, default=dict)),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                ("file_url", models.URLField(blank=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AnalyticsEvent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event_type", models.CharField(max_length=100)),
                ("event_data", models.JSONField(blank=True, default=dict)),
                ("session_id", models.CharField(blank=True, max_length=255)),
                ("retention_months", models.PositiveSmallIntegerField(default=24)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analytics_events",
                        to="organizations.branch",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
