# Generated by Django 6.0.6 on 2026-06-11 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('customers', '0001_initial'),
        ('operations', '0001_initial'),
        ('organnizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticsevent',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='analyticsevent',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_events', to='organnizations.organization'),
        ),
        migrations.AddField(
            model_name='analyticsevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailybranchmetric',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_branch_metrics', to='organnizations.branch'),
        ),
        migrations.AddField(
            model_name='dailybranchmetric',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_branch_metrics', to='organnizations.organization'),
        ),
        migrations.AddField(
            model_name='dailyemployeemetric',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_metrics', to='operations.employee'),
        ),
        migrations.AddField(
            model_name='dailyemployeemetric',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_employee_metrics', to='organnizations.organization'),
        ),
        migrations.AddField(
            model_name='dailymetric',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_metrics', to='organnizations.branch'),
        ),
        migrations.AddField(
            model_name='dailymetric',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_metrics', to='organnizations.organization'),
        ),
        migrations.AddField(
            model_name='report',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='organnizations.organization'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['organization', 'event_type', 'created_at'], name='analytics_a_organiz_0566af_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['organization', 'created_at'], name='analytics_a_organiz_085874_idx'),
        ),
        migrations.AddIndex(
            model_name='dailybranchmetric',
            index=models.Index(fields=['branch', 'date'], name='analytics_d_branch__e07f74_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailybranchmetric',
            constraint=models.UniqueConstraint(fields=('organization', 'branch', 'date'), name='uniq_daily_branch_metric_per_date'),
        ),
        migrations.AddIndex(
            model_name='dailyemployeemetric',
            index=models.Index(fields=['employee', 'date'], name='analytics_d_employe_a57d1a_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailyemployeemetric',
            constraint=models.UniqueConstraint(fields=('organization', 'employee', 'date'), name='uniq_daily_employee_metric_per_date'),
        ),
        migrations.AddIndex(
            model_name='dailymetric',
            index=models.Index(fields=['organization', 'date'], name='analytics_d_organiz_2a4001_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailymetric',
            constraint=models.UniqueConstraint(fields=('organization', 'branch', 'date'), name='uniq_daily_metric_per_branch_date'),
        ),
    ]
