# Generated by Django 6.0.6 on 2026-06-12 09:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0002_initial"),
        ("operations", "0001_initial"),
        ("organizations", "0003_retentionpolicy"),
    ]

    operations = [
        migrations.CreateModel(
            name="Goal",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "metric",
                    models.CharField(
                        choices=[
                            ("revenue", "Revenue"),
                            ("bookings", "Bookings"),
                            ("new_customers", "New Customers"),
                            ("retention", "Retention"),
                            ("nps", "NPS"),
                            ("custom", "Custom"),
                        ],
                        max_length=20,
                    ),
                ),
                ("target_value", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "current_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("achieved", "Achieved"),
                            ("missed", "Missed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("reward_description", models.CharField(blank=True, max_length=255)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goals",
                        to="organizations.branch",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goals",
                        to="operations.employee",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goals",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-period_start"],
            },
        ),
        migrations.CreateModel(
            name="GoalMilestone",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("threshold_percent", models.PositiveSmallIntegerField()),
                ("reward_description", models.CharField(blank=True, max_length=255)),
                ("reached_at", models.DateTimeField(blank=True, null=True)),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestones",
                        to="analytics.goal",
                    ),
                ),
            ],
            options={
                "ordering": ["threshold_percent"],
            },
        ),
        migrations.AddIndex(
            model_name="goal",
            index=models.Index(
                fields=["organization", "status"], name="analytics_g_organiz_0d615e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="goalmilestone",
            constraint=models.UniqueConstraint(
                fields=("goal", "threshold_percent"),
                name="uniq_goal_milestone_threshold",
            ),
        ),
    ]
