# Generated by Django 6.0.6 on 2026-06-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("financials", "0001_initial"),
        (
            "organizations",
            "0002_organization_building_number_organization_city_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="einvoice",
            name="invoice_hash",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="einvoice",
            name="ubl_xml",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="zatcadevice",
            name="compliance_request_id",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="zatcadevice",
            name="csid_secret_encrypted",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="zatcadevice",
            name="compliance_csid",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="zatcadevice",
            name="production_csid",
            field=models.TextField(blank=True),
        ),
        migrations.AddConstraint(
            model_name="einvoice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("icv__gt", 0)),
                fields=("zatca_device", "icv"),
                name="uniq_einvoice_icv_per_device",
            ),
        ),
    ]
