# Generated by Django 6.0.6 on 2026-06-14 02:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("financials", "0002_einvoice_invoice_hash_einvoice_ubl_xml_and_more"),
        ("organizations", "0003_retentionpolicy"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="documentsequence",
            constraint=models.UniqueConstraint(
                condition=models.Q(("branch__isnull", True)),
                fields=("organization", "document_type", "year"),
                name="uniq_document_sequence_no_branch",
            ),
        ),
    ]
