# Generated by Django 6.0.6 on 2026-06-16 22:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("financials", "0003_documentsequence_uniq_document_sequence_no_branch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentsequence",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("invoice", "Invoice"),
                    ("credit_note", "Credit Note"),
                    ("debit_note", "Debit Note"),
                    ("sale", "Sale"),
                    ("booking", "Booking"),
                    ("ticket", "Ticket"),
                    ("purchase_order", "Purchase Order"),
                ],
                max_length=20,
            ),
        ),
    ]
