# Generated by Django 6.0.6 on 2026-06-17 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("financials", "0004_alter_documentsequence_document_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="einvoice",
            name="credit_note",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="e_invoices",
                to="financials.creditnote",
            ),
        ),
        migrations.AddField(
            model_name="einvoice",
            name="debit_note",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="e_invoices",
                to="financials.debitnote",
            ),
        ),
        migrations.AddField(
            model_name="einvoice",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("invoice", "Tax Invoice"),
                    ("credit_note", "Credit Note"),
                    ("debit_note", "Debit Note"),
                ],
                default="invoice",
                max_length=20,
            ),
        ),
    ]
