# Generated by Django 6.0.6 on 2026-06-12 09:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0002_initial"),
        ("operations", "0001_initial"),
        ("organizations", "0003_retentionpolicy"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerSegment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "segment_type",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("dynamic", "Dynamic"),
                            ("ai", "AI-Generated"),
                        ],
                        default="manual",
                        max_length=10,
                    ),
                ),
                ("criteria", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("last_refreshed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_segments",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CustomerSegmentMembership",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segment_memberships",
                        to="customers.customer",
                    ),
                ),
                (
                    "segment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="customers.customersegment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Survey",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "survey_type",
                    models.CharField(
                        choices=[
                            ("nps", "NPS"),
                            ("post_visit", "Post-Visit"),
                            ("custom", "Custom"),
                        ],
                        default="nps",
                        max_length=20,
                    ),
                ),
                ("question", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("send_delay_hours", models.PositiveIntegerField(default=2)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="surveys",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SurveyResponse",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("score", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("comment", models.TextField(blank=True)),
                (
                    "sentiment",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("positive", "Positive"),
                            ("neutral", "Neutral"),
                            ("negative", "Negative"),
                        ],
                        max_length=10,
                    ),
                ),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="survey_responses",
                        to="operations.appointment",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="survey_responses",
                        to="customers.customer",
                    ),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="customers.survey",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="customersegment",
            constraint=models.UniqueConstraint(
                fields=("organization", "name"), name="uniq_segment_name_per_org"
            ),
        ),
        migrations.AddIndex(
            model_name="customersegmentmembership",
            index=models.Index(
                fields=["customer"], name="customers_c_custome_317454_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="customersegmentmembership",
            constraint=models.UniqueConstraint(
                fields=("segment", "customer"), name="uniq_segment_membership"
            ),
        ),
        migrations.AddIndex(
            model_name="surveyresponse",
            index=models.Index(
                fields=["survey", "created_at"], name="customers_s_survey__f72528_idx"
            ),
        ),
    ]
