# Generated by Django 6.0.6 on 2026-06-11 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("commerce", "0001_initial"),
        ("customers", "0001_initial"),
        ("operations", "0001_initial"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="appointment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sales",
                to="operations.appointment",
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sales",
                to="organizations.branch",
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sales",
                to="customers.customer",
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sales",
                to="operations.employee",
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sales",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="saleitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sale_items",
                to="commerce.product",
            ),
        ),
        migrations.AddField(
            model_name="saleitem",
            name="sale",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="commerce.sale",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="saleitem",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sale_items",
                to="commerce.service",
            ),
        ),
        migrations.AddField(
            model_name="servicecategory",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_categories",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="services",
                to="commerce.servicecategory",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["organization", "sku"], name="commerce_pr_organiz_71639a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["organization", "is_active"],
                name="commerce_pr_organiz_95903a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(
                fields=["organization", "created_at"],
                name="commerce_sa_organiz_65b017_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(
                fields=["organization", "status"], name="commerce_sa_organiz_e78ed6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(
                fields=["branch", "created_at"], name="commerce_sa_branch__49aa59_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(
                fields=["organization", "is_active"],
                name="commerce_se_organiz_e239aa_idx",
            ),
        ),
    ]
