# Generated by Django 6.0.6 on 2026-06-12 09:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "commerce",
            "0003_giftcard_giftcardtransaction_package_customerpackage_and_more",
        ),
        ("organizations", "0003_retentionpolicy"),
    ]

    operations = [
        migrations.CreateModel(
            name="PricingRule",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("time_based", "Time-Based"),
                            ("demand_based", "Demand-Based"),
                            ("segment_based", "Segment-Based"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "adjustment_type",
                    models.CharField(
                        choices=[("percent", "Percentage"), ("fixed", "Fixed Amount")],
                        default="percent",
                        max_length=10,
                    ),
                ),
                (
                    "adjustment_value",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("days_of_week", models.JSONField(blank=True, default=list)),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("valid_from", models.DateTimeField(blank=True, null=True)),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                (
                    "min_utilization_percent",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "max_utilization_percent",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("priority", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing_rules",
                        to="organizations.branch",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing_rules",
                        to="organizations.organization",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing_rules",
                        to="commerce.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-priority", "name"],
            },
        ),
    ]
