# Generated by Django 6.0.6 on 2026-06-12 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commerce", "0004_pricingrule"),
        ("customers", "0003_customersegment_customersegmentmembership_survey_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricingrule",
            name="segment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pricing_rules",
                to="customers.customersegment",
            ),
        ),
        migrations.AddField(
            model_name="pricingrule",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pricing_rules",
                to="commerce.service",
            ),
        ),
        migrations.AddIndex(
            model_name="pricingrule",
            index=models.Index(
                fields=["organization", "is_active"],
                name="commerce_pr_organiz_f9cf5c_idx",
            ),
        ),
    ]
