# Generated by Django 6.0.6 on 2026-06-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commerce", "0005_pricingrule_segment_pricingrule_service_and_more"),
        ("organizations", "0003_retentionpolicy"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(("stock_quantity__gte", 0)),
                name="product_stock_quantity_gte_0",
            ),
        ),
    ]
