# Generated by Django 6.0.6 on 2026-06-16 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_supplier_reorderrule_purchaseorder_purchaseorderline_and_more'),
        ('organizations', '0003_retentionpolicy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.UniqueConstraint(fields=('organization', 'po_number'), name='uniq_po_number_per_org'),
        ),
    ]
