# Generated by Django 6.0.6 on 2026-06-13 23:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai", "0001_initial"),
        ("organizations", "0003_retentionpolicy"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="airecommendation",
            constraint=models.UniqueConstraint(
                fields=("organization", "title", "status"),
                name="uniq_active_recommendation_per_title",
            ),
        ),
    ]
