# Generated by Django 6.0.6 on 2026-06-15 01:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai", "0002_airecommendation_uniq_active_recommendation_per_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="aimessage",
            name="ai_model",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="aimessage",
            name="ai_provider",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="aimessage",
            name="completion_tokens",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="aimessage",
            name="confidence",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=4, null=True
            ),
        ),
        migrations.AddField(
            model_name="aimessage",
            name="cost",
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="aimessage",
            name="latency_ms",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="aimessage",
            name="prompt_tokens",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="aimessage",
            name="prompt_version",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="aimessage",
            name="temperature",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=3, null=True
            ),
        ),
        migrations.AddField(
            model_name="airecommendation",
            name="ai_model",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="airecommendation",
            name="ai_provider",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="airecommendation",
            name="completion_tokens",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="airecommendation",
            name="confidence",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=4, null=True
            ),
        ),
        migrations.AddField(
            model_name="airecommendation",
            name="cost",
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="airecommendation",
            name="latency_ms",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="airecommendation",
            name="prompt_tokens",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="airecommendation",
            name="prompt_version",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="airecommendation",
            name="temperature",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=3, null=True
            ),
        ),
    ]
