# Generated by Django 6.0.6 on 2026-06-12 09:24

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_idempotencyrecord"),
    ]

    operations = [
        migrations.AlterField(
            model_name="idempotencyrecord",
            name="response_body",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
            ),
        ),
    ]
